### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by Handsomekaizer** [Fuckrrr247/pornhub-clone#1]
Hello, great work, 
I am using this pornhub clone template to create my own tube site but the problem am having is that I cannot place ads in the javascript codes since I am new to javascript. Please can you show me how and where to place the ads. These are the ads codes

<div data-awe-container-id="699335" style="display:inline-block;width:300px;height:250px;"></div><script src="https://awmbed.com/embed/vb?c=699335&categoryName=girl&filters=&pageName=listpage&color=black_yellow&psid=Ubonganthony&pstool=316_2&siteId=jasmin&cobrandId=&psprogram=revs&campaign_id=&ms_notrack=1&subAffId={SUBAFFID}"></script>

Or in iframe
<iframe width="300" height="250" style="display:inline-block;border:none;" src="https://pt.pwmctl.com/avb/straight/hardcore/1_scene?targetCategory=girl&landingTarget=signup&width=300&height=250&psid=Ubonganthony&tags=&filters=&banner=01&pstool=501_101&site=jasmin&cobrandId=&psprogram=revs&campaign_id=&subAffId={SUBAFFID}"></iframe>

Thanks

**Comment by Fuckrrr247** [comment]
Since I am using a third party websites for showing content on this website so you can't put mid roll ads in videos but you can add some banner ads and popup ads. Just add the script tag provided by your ad providers and put it inside index.html and for iframe ads you have to write the code in jsx format not HTML. 
I'm not sure all these step will work or not but give it a try.

**Comment by Handsomekaizer** [comment]
Thank you very much
